- platform: mqtt
  name: "sproeier voortuin"
  command_topic: "cmnd/dragon33/POWER1"
  state_topic: "stat/dragon33/POWER1"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
  icon: 'mdi:flower'

# Electro dragon Dual 02
- platform: mqtt
  name: "sproeier achtertuin"
  command_topic: "cmnd/dragon33/POWER2"
  state_topic: "stat/dragon33/POWER2"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
  icon: 'mdi:flower'

# Sproeitijd switch
- platform: template
  switches:
    sproei_timer:
      value_template: "{{ is_state('input_boolean.sproei_timer', 'on') }}"
      turn_on:
        - service: input_boolean.turn_on
          entity_id: input_boolean.sproei_timer
      turn_off:
        - service: input_boolean.turn_off
          entity_id: input_boolean.sproei_timer
